name: Asterisk
version: 0.2.12
slug: asterisk
description: PBX server for SIP devices like doorbells and phones
url: https://github.com/TECH7Fox/Asterisk-add-on
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
homeassistant_api: true
boot: auto
stage: experimental
map:
  - config:rw
  - ssl
options:
  ami_password: c32d3bd655d9226ffc062751ab9d1058
  auto_add: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ami_password: password
  auto_add: bool
  certfile: str
  keyfile: str
ports:
  "10000": 10000
  "10001": 10001
  "10002": 10002
  "10003": 10003
  "10004": 10004
  "10005": 10005
  "10006": 10006
  "10007": 10007
  "10008": 10008
  5038/tcp: 5038
  8089/tcp: 8089
  8088/tcp: 8088
  5060/tcp: 5060
  5060/udp: 5060
  5160/tcp: 5160
  5160/udp: 5160
  4569/udp: 4569
  2727/udp: 2727
ports_description:
  "10000": RTP
  "10001": RTP
  "10002": RTP
  "10003": RTP
  "10004": RTP
  "10005": RTP
  "10006": RTP
  "10007": RTP
  "10008": RTP
  5038/tcp: Port for AMI
  8089/tcp: Port for WSS
  8088/tcp: Port for WS
  5060/tcp: Port for SIP
  5060/udp: Port for SIP
  5160/tcp: Port for SIP
  5160/udp: Port for SIP
  4569/udp: Port for IAX2
  2727/udp: Port for MGCP
